#!/bin/sh

PROG="platform"
PROG_PATH="/data/app/$PROG"
MSG_PREFIX=" *"
echo "$MSG_PREFIX start install $PROG"

systemctl stop platform.service

if [ -d "$PROG_PATH" ] ; then
        rm -rf $PROG_PATH
fi

mkdir -p $PROG_PATH
mkdir -p $PROG_PATH/logs

cp -v -n -r bin $PROG_PATH/bin
cp -v -n -r conf $PROG_PATH/conf
cp -v -n -r lib $PROG_PATH/lib

cp -v -n -r lib $PROG $PROG.service $PROG_PATH/

ln -s $PROG_PATH/$PROG.service /etc/systemd/system/$PROG.service 

chmod 755 $PROG_PATH/bin/$PROG
chmod 755 $PROG_PATH/$PROG

if [ -x "/data/app/nodejs/bin/node" ] ; then
	echo "$MSG_PREFIX installed nodejs"
else
	echo "$MSG_PREFIX not install nodejs"
	exit 1
fi

systemctl daemon-reload

systemctl enable platform.service

systemctl start platform.service

echo "$MSG_PREFIX install sucess $PROG"

service $PROG start


