#!/bin/sh

PROG="platform"
PROG_PATH="/data/app/$PROG"
MSG_PREFIX=" *"
echo "$MSG_PREFIX start install $PROG"

service platform stop

if [ -d "$PROG_PATH" ] ; then
        rm -rf $PROG_PATH
fi

mkdir -p $PROG_PATH

cp -v -n -r bin $PROG_PATH/bin
cp -v -n -r conf $PROG_PATH/conf
cp -v -n -r lib $PROG_PATH/lib

cp -v -n -r lib $PROG $PROG_PATH/

if [ -f "/etc/init.d/$PROG" ] ; then
	echo "$MSG_PREFIX /etc/init.d/$PROG  already exist delete"
	rm -f /etc/init.d/$PROG
fi

ln -s PROG_PATH/$PROG /etc/init.d/$PROG

chmod 755 PROG_PATH/$PROG
chmod 755 /etc/init.d/$PROG

if [ -x "/usr/bin/node" ] ; then
	echo "$MSG_PREFIX install nodejs"
else
	echo "$MSG_PREFIX not install nodejs"
	exit 1
fi

if [ -f "/etc/rc0.d/K50$PROG" ] ; then
	echo "$MSG_PREFIX not need add start for boot"
else
	echo "$MSG_PREFIX add start for boot"
	update-rc.d  $PROG defaults 50
fi


echo "$MSG_PREFIX install sucess $PROG"

service $PROG start


